### ISSUE TITLE
   #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"

### ISSUE THREAD

**Issue by Marietto2008** [stantonious/ss-apps#3]
Hello.

I tried to install pi-apps/br on the jetson nano with this command :

root@zi-desktop:/home/zi/Desktop# pip install git+https://git@github.com/stantonious/ss-apps.git#subdirectory="pi-apps/br"

but at some point this error stopped the installation :

#error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"

I've saved the log file here :

https://pastebin.ubuntu.com/p/ssPRCVSqyN/

how to fix it ?

**Comment by stantonious** [comment]
It appears you're missing some system dependencies.  Please see:
https://github.com/stantonious/ss-apps/blob/master/setup/scripts/ss-setup.sh#L9
https://github.com/stantonious/ss-apps/blob/master/setup/scripts/ss-setup.sh#L24

 I strongly recommend that you use a virtualenv https://github.com/stantonious/ss-apps/blob/master/setup/scripts/ss-setup.sh#L28

I have only installed this on a Raspberry Pi 3b and 4b (Raspian).  Any other hardware/OS may not be supported.

**Comment by Marietto2008** [comment]
I made some progress,but it freezed later :

```
 Building wheel for ss-br-apps (setup.py) ... done
  Created wheel for ss-br-apps: filename=ss_br_apps-1.0-py3-none-any.whl size=13417 sha256=39e9164c216fa00be9af8f4747a79f1fd8971376661fb32fa8fab648c4c637c5
  Stored in directory: /tmp/pip-ephem-wheel-cache-abxbix0q/wheels/60/25/18/5b94bc0aa2e92dd52d5b763849a8c2c884f120397049555480
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4_blnfz2
       cwd: /tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932/
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  ERROR: Command errored out with exit status -4:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-74z3lmhr/numba_6786988fb4a64ce0a794bc3ec2663932
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nmiktnt2
       cwd: /tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/
  Complete output (11 lines):
  running bdist_wheel
  /usr/bin/python /tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built ss-br-apps
Failed to build numba llvmlite
Installing collected packages: llvmlite, threadpoolctl, scipy, numba, cffi, soundfile, scikit-learn, resampy, spidev, pika, librosa, ss-br-apps
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9qjmo4nq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite
         cwd: /tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/
    Complete output (14 lines):
    running install
    running build
    got version from file /tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
    running build_ext
    /usr/bin/python /tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 220, in <module>
        main()
      File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 210, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/usr/bin/python' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74z3lmhr/llvmlite_4c5ffa2dff214dcdaa90fb0966b147bb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9qjmo4nq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite Check the logs for full command output.

```

**Comment by Marietto2008** [comment]
so,you say that your code has been written for armhf ? I'm using arm64 and it will not work ? just in case I can emulate armhf / raspberry on the jetson nano with qemu + kvm.
